import path from "node:path";
import type { Finding, ScanResult, Severity } from "./types.js";
import { groupBy } from "./utils/collections.js";
import { percent } from "./utils/text.js";

const severityRank: Record<Severity, number> = { high: 2, medium: 1, low: 0 };

/**
 * Renders findings as a fix plan addressed to a coding agent
 * (Claude Code, Cursor, Codex, ...). The scanner finds it; your agent fixes it.
 */
export function renderFixPlan(result: ScanResult): string {
  const repoName = path.basename(result.rootPath) || result.rootPath;
  if (result.findings.length === 0) {
    return `# Slop fix plan for ${repoName}\n\nNo findings — nothing to fix at the current threshold.\n`;
  }

  const byFile = [...groupBy(result.findings, (finding) => finding.file).entries()]
    .sort((a, b) => fileWeight(b[1]) - fileWeight(a[1]));

  const lines: string[] = [
    `# Slop fix plan for ${repoName}`,
    "",
    `Generated by ai-slop-remover. ${result.findings.length} finding(s) across ${byFile.length} file(s). Slop Score: ${result.score.score}/100 (${result.score.grade}).`,
    "",
    "Instructions for the agent applying this plan:",
    "",
    "1. Work through the files in order; finish one file before starting the next.",
    "2. Do not change runtime behavior unless a fix explicitly asks you to implement missing behavior.",
    "3. Run the project's tests (and typecheck, if present) after each file; revert the file if they break.",
    "4. If a fix looks wrong in context, skip it and leave a one-line note explaining why.",
    ""
  ];

  for (const [file, findings] of byFile) {
    lines.push(`## ${file}`, "");
    const ordered = [...findings].sort(
      (a, b) => severityRank[b.severity] - severityRank[a.severity] || a.line_start - b.line_start
    );
    ordered.forEach((finding, index) => {
      lines.push(`${index + 1}. **Line ${finding.line_start}${finding.line_end > finding.line_start ? `-${finding.line_end}` : ""} — ${finding.title}** (${finding.severity}, confidence ${percent(finding.confidence)})`);
      lines.push(`   - Problem: ${finding.explanation}`);
      lines.push(`   - Fix: ${finding.fix_hint}`);
      if (finding.evidence) lines.push(`   - Evidence: \`${finding.evidence.replaceAll("`", "'")}\``);
      lines.push("");
    });
  }

  return `${lines.join("\n")}`;
}

function fileWeight(findings: Finding[]): number {
  return findings.reduce((sum, finding) => sum + (severityRank[finding.severity] + 1) * finding.confidence, 0);
}
